### ISSUE TITLE
Zip code is invalid on AddressElement form

### ISSUE THREAD

**Issue by dianaow** [pevey/sveltekit-stripe#2]
What should be the correct way of specifying the zip code? What are the form value limitations?

![Screenshot 2024-03-07 at 12 54 31 PM](https://github.com/pevey/sveltekit-stripe/assets/33983719/ab2c38a3-d5d9-41b2-9b09-06ebae0632da)

**Comment by pevey** [comment]
Places like the Stripe discord have a lot more people who can help you with these sorts of questions. The Stripe docs are also very good. Zip codes don't have that many digits. They also have to be actual zip codes.
